// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kHCKEcYWcmWFvnZ511qGxj
// Component: 0YsmMrCfj-lRqMD
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: gUUwcfxLK8qsLUf/component
import Button from "../../Button"; // plasmic-import: ID408cV-KrF2KD/component
import Footer from "../../Footer"; // plasmic-import: BMHqzSi3MkEVmjN/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_saa_s_website.module.css"; // plasmic-import: kHCKEcYWcmWFvnZ511qGxj/projectcss
import sty from "./PlasmicPricing.module.css"; // plasmic-import: 0YsmMrCfj-lRqMD/css
import Icon14Icon from "./icons/PlasmicIcon__Icon14"; // plasmic-import: cwgNtJiJOMqi67j/icon
import ArrowRightsvgIcon from "./icons/PlasmicIcon__ArrowRightsvg"; // plasmic-import: Q1nyCXo_O37SG_I/icon

export const PlasmicPricing__VariantProps = new Array();

export const PlasmicPricing__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicPricing__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div className={classNames(projectcss.all, sty.freeBox__kcPB)}>
            <div className={classNames(projectcss.all, sty.freeBox__utf2S)}>
              <div className={classNames(projectcss.all, sty.freeBox__mjQoq)} />
              <p.Stack
                as={"div"}
                data-plasmic-name={"foreground"}
                data-plasmic-override={overrides.foreground}
                hasGap={true}
                className={classNames(projectcss.all, sty.foreground)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__liBaJ)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__tYu6X)}
                  >
                    <h1
                      data-plasmic-name={"h1"}
                      data-plasmic-override={overrides.h1}
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1
                      )}
                    >
                      {"Pricing plans"}
                    </h1>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ihRh
                    )}
                  >
                    {
                      "Nascetur nascetur ridiculus scelerisque adipiscing a nascetur varius sed eu a ad semper a est nec litora ante at orci rhoncus a varius auctor aliquam inceptos vestibulum ridiculus."
                    }
                  </div>
                </p.Stack>
                <div className={classNames(projectcss.all, sty.freeBox__rAnfz)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mlgXb)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___5QSXy
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tebye
                        )}
                      >
                        {"Starter"}
                      </div>
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__u1NZ5
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__sCamt
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__opu8C
                            )}
                          >
                            {"$"}
                          </div>
                          <h2
                            className={classNames(
                              projectcss.all,
                              projectcss.h2,
                              projectcss.__wab_text,
                              sty.h2__kuLLa
                            )}
                          >
                            {"8"}
                          </h2>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__rt0Vk
                          )}
                        >
                          {"/month"}
                        </div>
                      </p.Stack>
                    </p.Stack>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__zwGq)}
                    />

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__foxr8)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__t5Rpq
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___4078C
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__wsRpm
                            )}
                          >
                            <Icon14Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__bnCst
                              )}
                              role={"img"}
                            />
                          </div>
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__dfxCo
                              )}
                            >
                              <Icon14Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__dQV
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__hYh9A
                            )}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__wAj0
                                )}
                              >
                                {"Label"}
                              </div>
                            ) : null}
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__p69Ob
                              )}
                            >
                              {
                                "Vestibulum mollis odio dictum ultrices facilisis molestie vestibulum"
                              }
                            </div>
                          </p.Stack>
                        </p.Stack>
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__m3NXh
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__sn2Cl
                            )}
                          >
                            <Icon14Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__nUAfM
                              )}
                              role={"img"}
                            />
                          </div>
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__o2Dy8
                              )}
                            >
                              <Icon14Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__hwV7T
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___63Ow1
                            )}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__frRm8
                                )}
                              >
                                {"Label"}
                              </div>
                            ) : null}
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__zMzFa
                              )}
                            >
                              {"Mus consequat a justo"}
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </p.Stack>
                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__eMvZi
                          )}
                        >
                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button___1VSr
                            )}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__jNkTv
                                )}
                                role={"img"}
                              />
                            }
                            showEndIcon={true}
                            submitsForm={true}
                          >
                            {"Buy starter"}
                          </Button>
                        </div>
                      ) : null}
                    </p.Stack>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__qNoG7)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__tWmFa)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ytRc9
                        )}
                      >
                        {"Pro"}
                      </div>
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___9KEa
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___7Qp4D
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__hFzE
                            )}
                          >
                            {"$"}
                          </div>
                          <h2
                            className={classNames(
                              projectcss.all,
                              projectcss.h2,
                              projectcss.__wab_text,
                              sty.h2__wY1Q6
                            )}
                          >
                            {"16"}
                          </h2>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__gqu0U
                          )}
                        >
                          {"/month"}
                        </div>
                      </p.Stack>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___9UwQi
                      )}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__zaXCi
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__y3KHn
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__xJkyq
                            )}
                          >
                            <Icon14Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__xcuuw
                              )}
                              role={"img"}
                            />
                          </div>
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__j5JUk
                              )}
                            >
                              <Icon14Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__g2ZSh
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__opw4
                            )}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__dnrCd
                                )}
                              >
                                {"Label"}
                              </div>
                            ) : null}
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___57Ptc
                              )}
                            >
                              {
                                "Ligula primis mollis sem dignissim semper lectus parturient"
                              }
                            </div>
                          </p.Stack>
                        </p.Stack>
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__vGby
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__nzIAw
                            )}
                          >
                            <Icon14Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__oxP03
                              )}
                              role={"img"}
                            />
                          </div>
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__b3Kx
                              )}
                            >
                              <Icon14Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__fBtvl
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__rkTp0
                            )}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__e1AKo
                                )}
                              >
                                {"Label"}
                              </div>
                            ) : null}
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___5ABpf
                              )}
                            >
                              {"A curabitur dignissim pharetra porta suscipit"}
                            </div>
                          </p.Stack>
                        </p.Stack>
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__pv1Wf
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__oTmE
                            )}
                          >
                            <Icon14Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg___7Hxzk
                              )}
                              role={"img"}
                            />
                          </div>
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__l9ArJ
                              )}
                            >
                              <Icon14Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__ioj4Y
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__mvCOk
                            )}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__x3OhL
                                )}
                              >
                                {"Label"}
                              </div>
                            ) : null}
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__sUctI
                              )}
                            >
                              {
                                "Condimentum diam a et sapien praesent potenti torquent a eros"
                              }
                            </div>
                          </p.Stack>
                        </p.Stack>
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__rYqcV
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__qvPmh
                            )}
                          >
                            <Icon14Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg___2Foa
                              )}
                              role={"img"}
                            />
                          </div>
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox___1HDiM
                              )}
                            >
                              <Icon14Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__aKx7S
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__u8Trp
                            )}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___8SrkJ
                                )}
                              >
                                {"Label"}
                              </div>
                            ) : null}
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__yQCa
                              )}
                            >
                              {"Conubia in hac eu elementum sodales"}
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </p.Stack>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___7QI65
                        )}
                      >
                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button___72RP9
                          )}
                          color={"blue"}
                          endIcon={
                            <ArrowRightsvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__sMRu
                              )}
                              role={"img"}
                            />
                          }
                          shape={"rounded"}
                          showEndIcon={true}
                          submitsForm={true}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__wVt5P
                            )}
                          >
                            {"Buy pro"}
                          </div>
                        </Button>
                      </div>
                    </p.Stack>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__r7NF)}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__bCnCy)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__ovRF)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___9OCnh
                        )}
                      >
                        {"Team"}
                      </div>
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___3NC8Q
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__oVKeq
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__nalyM
                            )}
                          >
                            {"$"}
                          </div>
                          <h2
                            className={classNames(
                              projectcss.all,
                              projectcss.h2,
                              projectcss.__wab_text,
                              sty.h2__xIOjm
                            )}
                          >
                            {"10"}
                          </h2>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__uIRix
                          )}
                        >
                          {"/member"}
                        </div>
                      </p.Stack>
                    </p.Stack>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__zshtD)}
                    />

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__pyLl0)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__nnRQ
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__j7Yur
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__hpQ3R
                            )}
                          >
                            <Icon14Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__xyg5F
                              )}
                              role={"img"}
                            />
                          </div>
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__ftu7S
                              )}
                            >
                              <Icon14Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__sUPrh
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__dnH40
                            )}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__dDiJr
                                )}
                              >
                                {"Label"}
                              </div>
                            ) : null}
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__dhWzY
                              )}
                            >
                              {"Ad nam curae a potenti platea"}
                            </div>
                          </p.Stack>
                        </p.Stack>
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__i2AdJ
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__za6EH
                            )}
                          >
                            <Icon14Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__mBj7
                              )}
                              role={"img"}
                            />
                          </div>
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox___6TpYo
                              )}
                            >
                              <Icon14Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___6L8
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__p2JF
                            )}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__cYL
                                )}
                              >
                                {"Label"}
                              </div>
                            ) : null}
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___67ECp
                              )}
                            >
                              {
                                "A adipiscing scelerisque pretium consectetur sem"
                              }
                            </div>
                          </p.Stack>
                        </p.Stack>
                        {true ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__yZcVh
                            )}
                          >
                            <Button
                              className={classNames(
                                "__wab_instance",
                                sty.button__kqQdG
                              )}
                              endIcon={
                                <ArrowRightsvgIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__nmESp
                                  )}
                                  role={"img"}
                                />
                              }
                              showEndIcon={true}
                              submitsForm={true}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__rciez
                                )}
                              >
                                {"Buy Team"}
                              </div>
                            </Button>
                          </div>
                        ) : null}
                      </p.Stack>
                    </p.Stack>
                  </div>
                </div>
              </p.Stack>
            </div>
          </div>
          <div
            data-plasmic-name={"faQs"}
            data-plasmic-override={overrides.faQs}
            className={classNames(projectcss.all, sty.faQs)}
          >
            <div
              data-plasmic-name={"container5"}
              data-plasmic-override={overrides.container5}
              className={classNames(projectcss.all, sty.container5)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__pUCd
                )}
              >
                {"FAQ"}
              </h2>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___3EU9X
                )}
              >
                {
                  "Nascetur nascetur ridiculus scelerisque adipiscing a nascetur varius sed eu a ad semper a est nec litora ante at orci rhoncus a varius auctor aliquam inceptos vestibulum ridiculus."
                }
              </div>
            </div>
            <p.Stack
              as={"div"}
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns)}
            >
              <div className={classNames(projectcss.all, sty.column___6SsBz)}>
                <div
                  data-plasmic-name={"accordion4"}
                  data-plasmic-override={overrides.accordion4}
                  className={classNames(projectcss.all, sty.accordion4)}
                >
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__meL49
                    )}
                  >
                    {"The standard Lorem Ipsum passage, used since the 1500s"}
                  </h5>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jYnDf
                    )}
                  >
                    {
                      "Nascetur nascetur ridiculus scelerisque adipiscing a nascetur varius sed eu a ad semper a est nec litora ante at orci rhoncus a varius auctor aliquam inceptos vestibulum ridiculus."
                    }
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__tLqo2)}>
                <div
                  data-plasmic-name={"accordion8"}
                  data-plasmic-override={overrides.accordion8}
                  className={classNames(projectcss.all, sty.accordion8)}
                >
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__gh10T
                    )}
                  >
                    {"The standard Lorem Ipsum passage, used since the 1500s"}
                  </h5>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lJnM
                    )}
                  >
                    {
                      "Nascetur nascetur ridiculus scelerisque adipiscing a nascetur varius sed eu a ad semper a est nec litora ante at orci rhoncus a varius auctor aliquam inceptos vestibulum ridiculus."
                    }
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__qgeQk)}>
                <div
                  data-plasmic-name={"accordion9"}
                  data-plasmic-override={overrides.accordion9}
                  className={classNames(projectcss.all, sty.accordion9)}
                >
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__vIlSx
                    )}
                  >
                    {"The standard Lorem Ipsum passage, used since the 1500s"}
                  </h5>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fDW
                    )}
                  >
                    {
                      "Nascetur nascetur ridiculus scelerisque adipiscing a nascetur varius sed eu a ad semper a est nec litora ante at orci rhoncus a varius auctor aliquam inceptos vestibulum ridiculus."
                    }
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__bBhY6)}>
                <div
                  data-plasmic-name={"accordion10"}
                  data-plasmic-override={overrides.accordion10}
                  className={classNames(projectcss.all, sty.accordion10)}
                >
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__cfz29
                    )}
                  >
                    {"The standard Lorem Ipsum passage, used since the 1500s"}
                  </h5>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gsfmS
                    )}
                  >
                    {
                      "Nascetur nascetur ridiculus scelerisque adipiscing a nascetur varius sed eu a ad semper a est nec litora ante at orci rhoncus a varius auctor aliquam inceptos vestibulum ridiculus."
                    }
                  </div>
                </div>
              </div>
            </p.Stack>
          </div>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "foreground",
    "h1",
    "faQs",
    "container5",
    "columns",
    "accordion4",
    "accordion8",
    "accordion9",
    "accordion10",
    "footer"
  ],

  header: ["header"],
  foreground: ["foreground", "h1"],
  h1: ["h1"],
  faQs: [
    "faQs",
    "container5",
    "columns",
    "accordion4",
    "accordion8",
    "accordion9",
    "accordion10"
  ],

  container5: ["container5"],
  columns: ["columns", "accordion4", "accordion8", "accordion9", "accordion10"],
  accordion4: ["accordion4"],
  accordion8: ["accordion8"],
  accordion9: ["accordion9"],
  accordion10: ["accordion10"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicPricing__ArgProps,
          internalVariantPropNames: PlasmicPricing__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPricing__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPricing";
  } else {
    func.displayName = `PlasmicPricing.${nodeName}`;
  }
  return func;
}

export const PlasmicPricing = Object.assign(
  // Top-level PlasmicPricing renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    foreground: makeNodeComponent("foreground"),
    h1: makeNodeComponent("h1"),
    faQs: makeNodeComponent("faQs"),
    container5: makeNodeComponent("container5"),
    columns: makeNodeComponent("columns"),
    accordion4: makeNodeComponent("accordion4"),
    accordion8: makeNodeComponent("accordion8"),
    accordion9: makeNodeComponent("accordion9"),
    accordion10: makeNodeComponent("accordion10"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicPricing
    internalVariantProps: PlasmicPricing__VariantProps,
    internalArgProps: PlasmicPricing__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicPricing;
/* prettier-ignore-end */
